# Site settings
title: The Feynman Challenge
email: sigil.w3n@gmail.com
description: Self-Studying The Feynman Lectures on Physics.
baseurl: "" 
url: "http://feynman.study"

# Build settings
markdown: kramdown
theme: minima
css: github-markdown-light.css

kramdown:
  math_engine: mathjax

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
