# Site settings
title: The Feynman Challenge
email: sigil.w3n@gmail.com
description: Self-Studying The Feynman Lectures on Physics.
baseurl: "" 
url: "http://feynman.study"

# Build settings
markdown: kramdown
theme: minima
css: github-markdown-light.css

kramdown:
  math_engine: mathjax
